=== api-evangelist/ipinfo/json-schema/ipinfo-full-response-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/ipinfo/main/json-schema/ipinfo-full-response-schema.json",
  "title": "FullResponse",
  "description": "FullResponse schema from IPinfo API",
  "type": "object",
  "properties": {
    "ip": {
      "type": "string",
      "example": "66.87.125.72"
    },
    "bogon": {
      "type": "boolean",
      "example": false
    },
    "hostname": {
      "type": "string",
      "example": "ip-66-87-125-72.spfdma.spcsdns.net"
    },
    "city": {
      "type": "string",
      "example": "Springfield"
    },
    "region": {
      "type": "string",
      "example": "Massachusetts"
    },
    "country": {
      "type": "string",
      "example": "US"
    },
    "loc": {
      "type": "string",
      "example": "42.0999,-72.5783"
    },
    "postal": {
      "type": "string",
      "example": "01105"
    },
    "timezone": {
      "type": "string",
      "example": "America/New_York"
    },
    "org": {
      "type": "string",
      "example": "AS51501 Khabarovsk home networks Ltd"
    },
    "asn": {
      "$ref": "./ipinfo-asn-response-schema.json"
    },
    "company": {
      "$ref": "./ipinfo-company-response-schema.json"
    },
    "carrier": {
      "$ref": "./ipinfo-carrier-response-schema.json"
    },
    "privacy": {
      "$ref": "./ipinfo-privacy-response-schema.json"
    },
    "domains": {
      "$ref": "./ipinfo-domains-response-schema.json"
    }
  },
  "required": [
    "ip"
  ]
}

=== api-evangelist/ipinfo/examples/ipinfo-full-response-example.json
{
  "ip": "66.87.125.72",
  "bogon": false,
  "hostname": "ip-66-87-125-72.spfdma.spcsdns.net",
  "city": "Springfield",
  "region": "Massachusetts",
  "country": "US",
  "loc": "42.0999,-72.5783",
  "postal": "01105",
  "timezone": "America/New_York",
  "org": "AS51501 Khabarovsk home networks Ltd",
  "asn": null,
  "company": null,
  "carrier": null,
  "privacy": null,
  "domains": null
}
